#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mitogen
Version  : 0.2.9
Release  : 1
URL      : https://files.pythonhosted.org/packages/67/65/612aa75b9b16ef4d81d1f840ce59f01a7b348ee54df8966be0aeea7e7848/mitogen-0.2.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/67/65/612aa75b9b16ef4d81d1f840ce59f01a7b348ee54df8966be0aeea7e7848/mitogen-0.2.9.tar.gz
Summary  : Library for writing distributed self-replicating programs.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mitogen-license = %{version}-%{release}
Requires: mitogen-python = %{version}-%{release}
Requires: mitogen-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Mitogen
<!-- [![Build Status](https://travis-ci.org/dw/mitogen.png?branch=master)](https://travis-ci.org/dw/mitogen}) -->
<a href="https://mitogen.networkgenomics.com/">Please see the documentation</a>.

%package license
Summary: license components for the mitogen package.
Group: Default

%description license
license components for the mitogen package.


%package python
Summary: python components for the mitogen package.
Group: Default
Requires: mitogen-python3 = %{version}-%{release}

%description python
python components for the mitogen package.


%package python3
Summary: python3 components for the mitogen package.
Group: Default
Requires: python3-core
Provides: pypi(mitogen)

%description python3
python3 components for the mitogen package.


%prep
%setup -q -n mitogen-0.2.9
cd %{_builddir}/mitogen-0.2.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599850946
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mitogen
cp %{_builddir}/mitogen-0.2.9/LICENSE %{buildroot}/usr/share/package-licenses/mitogen/38e1580f7dbac34a268ff5e2e72d5619047729bd
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mitogen/38e1580f7dbac34a268ff5e2e72d5619047729bd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
